### ISSUE TITLE
RuntimeError on Working With Data (6)

### ISSUE THREAD

**Issue by magicalcentipede** [MicrosoftLearning/mslearn-dp100#56]
Getting this error when running the notebook called "06 - Work with Data.ipynb". 

The error happens when running the block of code below
```

from azureml.core import Experiment, ScriptRunConfig, Environment
from azureml.widgets import RunDetails


# Create a Python environment for the experiment (from a .yml file)
env = Environment.from_conda_specification("experiment_env", "environment.yml")

# Get the training dataset
diabetes_ds = ws.datasets.get("diabetes dataset")

# Create a script config
script_config = ScriptRunConfig(source_directory=experiment_folder,
                              script='diabetes_training.py',
                              arguments = ['--regularization', 0.1, # Regularizaton rate parameter
                                           '--input-data', diabetes_ds.as_named_input('training_data')], # Reference to dataset
                              environment=env) 

# submit the experiment
experiment_name = 'mslearn-train-diabetes'
experiment = Experiment(workspace=ws, name=experiment_name)
run = experiment.submit(config=script_config)
RunDetails(run).show()
run.wait_for_completion()
```

The Stacktrace from logs below:

```
Traceback (most recent call last):
  File "diabetes_training.py", line 27, in <module>
    diabetes = run.input_datasets['training_data'].to_pandas_dataframe()
  File "/home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61/lib/python3.6/site-packages/azureml/data/_loggerfactory.py", line 132, in wrapper
    return func(*args, **kwargs)
  File "/home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61/lib/python3.6/site-packages/azureml/data/tabular_dataset.py", line 168, in to_pandas_dataframe
    dataflow = get_dataflow_for_execution(self._dataflow, 'to_pandas_dataframe', 'TabularDataset')
  File "/home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61/lib/python3.6/site-packages/azureml/data/_loggerfactory.py", line 132, in wrapper
    return func(*args, **kwargs)
  File "/home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61/lib/python3.6/site-packages/azureml/data/abstract_dataset.py", line 217, in _dataflow
    dataprep().api._datastore_helper._set_auth_type(self._registration.workspace)
  File "/home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61/lib/python3.6/site-packages/azureml/dataprep/api/_datastore_helper.py", line 185, in _set_auth_type
    get_engine_api().set_aml_auth(SetAmlAuthMessageArgument(auth_type, json.dumps(auth_value)))
  File "/home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/api.py", line 19, in get_engine_api
    _engine_api = EngineAPI()
  File "/home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/api.py", line 110, in __init__
    self._message_channel = launch_engine()
  File "/home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/engine.py", line 333, in launch_engine
    dependencies_path = runtime.ensure_dependencies()
  File "/home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61/lib/python3.6/site-packages/dotnetcore2/runtime.py", line 289, in ensure_dependencies
    raise RuntimeError(err_msg)
RuntimeError: Unable to retrieve .NET dependencies. Please make sure you are connected to the Internet and have a stable network connection.
```

It seems like the dotnetcore2 package is trying to download dependencies but failing. This may be due to a corporate firewall. If this is this case, it possible to install these manually?

**Comment by madiepev** [comment]
@magicalcentipede I'm not able to reproduce your error. Some questions to help you troubleshoot:
1. Did you complete the Create an Azure Machine Learning Workspace exercise? 
2. Are you running the code from the Jupyter application that you've launched from the Compute Instance?
3. Did you successfully run the code above this part to connect to a datastore to upload data and create a dataset?
Let me know if you have some more information so we can figure out what is causing this. If you think there's an issue with your workspace, you could also create a Support ticket so that they can see whether there is something going wrong from Azure ML's side.

**Comment by magicalcentipede** [comment]
Here are the answers:
1. I completed everything in the exercise except for cloning the Github Repo (blocked by corporate firewall). Instead, I manually copied over files onto the Jupiter instance.
2. Yes
3. Yes

Extra Info: 
Got the error below when running the script in the "07 - Work with Compute.ipynb" file. It seems like there was a client timeout. Makes me more certain there may be firewall issues going on that led to the error here as well.

```
Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-train-diabetes_1640056973_7e916f43/azureml-environment-setup/docker_env_checker.sh']

Materialized image not found on target: azureml/azureml_b2cc70078cd68f11125e50f07bf290ca


[2021-12-21T03:22:55.853249] Logging experiment preparation status in history service.
Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-train-diabetes_1640056973_7e916f43/azureml-environment-setup/docker_env_builder.sh']
Running: ['nvidia-docker', 'build', '-f', 'azureml-environment-setup/Dockerfile', '-t', 'azureml/azureml_b2cc70078cd68f11125e50f07bf290ca', '.']
Sending build context to Docker daemon  595.5kB
Step 1/15 : FROM mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20211029.v1@sha256:fda0c9dd1702f56aa5ce42ebeeda6af6b768d1cb18c04380af3ded4184eedb09
Get "https://mcr.microsoft.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)


CalledProcessError(1, ['nvidia-docker', 'build', '-f', 'azureml-environment-setup/Dockerfile', '-t', 'azureml/azureml_b2cc70078cd68f11125e50f07bf290ca', '.'])

Building docker image failed with exit code: 1



[2021-12-21T03:23:11.980703] Logging error in history service: Failed to run ['/bin/bash', '/tmp/azureml_runs/mslearn-train-diabetes_1640056973_7e916f43/azureml-environment-setup/docker_env_builder.sh'] 
 Exit code 1 
```

**Comment by madiepev** [comment]
@magicalcentipede I'm assuming you mean that you have some security restrictions within Azure that are blocking these actions for you. Network security on your personal device should not get in the way of e.g. cloning a repo to the compute instance, since that is running in Azure. If you indeed do have security restrictions within your Azure subscription, that is something that your admin can help you with. Alternatively, you can create an Azure free account if you want to complete the exercises without these issues: https://azure.microsoft.com/en-us/free/

**Comment by magicalcentipede** [comment]
Yes, thanks for clarifying; there are some security restrictions within Azure that are blocking these actions. All working well with a free Azure account!

**Comment by madiepev** [comment]
@magicalcentipede Great! Thanks for letting me know.
